heavy_metals = [
    "Titanium",
    "Vanadium",
    "Chromium",
    "Manganese",
    "Iron",
    "Cobalt",
    "Nickel",
    "Copper",
    "Zinc",
    "Gallium",
    "Germanium",
    "Arsenic",
    "Zirconium",
    "Niobium",
    "Molybdenum",
    "Technetium",
    "Ruthenium",
    "Rhodium",
    "Palladium",
    "Silver",
    "Cadmium",
    "Indium",
    "Tin",
    "Tellurium",
    "Lutetium",
    "Hafnium",
    "Tantalum",
    "Tungsten",
    "Rhenium",
    "Osmium",
    "Iridium",
    "Platinum",
    "Gold",
    "Mercury",
    "Thallium",
    "Lead",
    "Bismuth",
    "Polonium",
    "Astatine",
    "Lanthanum",
    "Cerium",
    "Praseodymium",
    "Neodymium",
    "Promethium",
    "Samarium",
    "Europium",
    "Gadolinium",
    "Terbium",
    "Dysprosium",
    "Holmium",
    "Erbium",
    "Thulium",
    "Ytterbium",
    "Actinium",
    "Thorium",
    "Protactinium",
    "Uranium",
    "Neptunium",
    "Plutonium",
    "Americium",
    "Curium",
    "Berkelium",
    "Californium",
    "Einsteinium",
    "Fermium",
    "Nobelium",
    "Radium",
    "Lawrencium",
    "Rutherfordium",
    "Dubnium",
    "Seaborgium",
    "Bohrium",
    "Hassium",
    "Meitnerium",
    "Darmstadtium",
    "Roentgenium",
    "Copernicium",
    "Nihonium",
    "Flerovium",
    "Moscovium",
    "Livermorium",
]
[Loading]
cols_to_drop = [
    "State Code",
    "County Code",
    "Local Site Name",
    "1st Max Non Overlapping Value",
    "1st NO Max DateTime",
    "2nd Max Non Overlapping Value",
    "2nd NO Max DateTime",
    "Date of Last Change",
    "Sample Duration",
    "Site Num",
    "Pollutant Standard",
    "Certification Indicator",
    "Completeness Indicator",
    "Parameter Code",
    "1st Max DateTime",
    "1st Max Value",
    "2nd Max DateTime",
    "2nd Max Value",
    "3rd Max DateTime",
    "3rd Max Value",
    "4th Max DateTime",
    "4th Max Value",
    "Method Name",
    ]
ignore_params = [
    "Average Ambient Temperature",
    "Average Ambient Pressure",
    "Acceptable PM2.5 AQI & Speciation Mass",
    "PM2.5 - Local Conditions",
    "Wind Direction - Resultant",
    "Wind Speed - Resultant",
    "Outdoor Temperature",
    "PM10 Total 0-10um STP",
    "Wind Speed - Scalar",
    "Sample Volume",
    "Ambient Min Temperature",
    "Ambient Max Temperature",
    "Relative Humidity",
    "Sample Min Baro Pressure",  # cspell: ignore baro
    "Sample Max Baro Pressure",
    "Sample Flow Rate CV - Quartz Filter",
    "Peak Wind Gust",
    "Std Dev Hz Wind Direction",
    "Relative Humidity ",
    "Wind Direction - Scalar",
    "Elapsed Sample Time",
    "Sample Flow Rate- CV",
    "Rain/melt precipitation",
    "Solar radiation",
    "PM2.5 Raw Data",
    "Barometric pressure",
    "PM10-2.5 - Local Conditions",
    "PM10 - LC",
    "SO2 max 5-min avg",
    "1,3-Butadiene",
]